USE [master]
GO

/****** Object:  Database [Default_BD_ICE_Alekseev]    Script Date: 01.03.2021 9:51:45 ******/
CREATE DATABASE [Default_BD_ICE_Alekseev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Default_BD_ICE_Alekseev', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Default_BD_ICE_Alekseev.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Default_BD_ICE_Alekseev_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Default_BD_ICE_Alekseev_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Default_BD_ICE_Alekseev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET ARITHABORT OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET  MULTI_USER 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Default_BD_ICE_Alekseev] SET  READ_WRITE 
GO


