USE [Traning_base_Alekseev] 
GO
CREATE TABLE employeess (
E_ID int IDENTITY (1,1) NOT NULL,
E_SURNAME VARCHAR(20) NOT NULL,
E_NAME VARCHAR(20) NOT NULL,
E_FNAME VARCHAR(30) NOT NULL,
E_BIRTHDAY DATE NULL,
E_SEX BIT NULL,
E_POST INT NULL,
E_ROOM INT NULL,
E_PHONE VARCHAR(10) NULL,
E_INN VARCHAR(12) NOT NULL,
E_PASP_NUMBER VARCHAR(12) NOT NULL,
E_PASP_ORG VARCHAR(50) NOT NULL,
E_PASP_DATE DATE NOT NULL,
E_ADRESS VARCHAR(80) NOT NULL,
CONSTRAINT PK_employeess PRIMARY KEY (E_ID)
)
GO
